### ISSUE TITLE
Printer cannot be located on Windows 10

### ISSUE THREAD

**Issue by TravelingTechGuy** [watson/ipp-printer#6]
I tried using the module on Windows 10. With the code provided in the README, and as a global module. In both cases, Windows could not see the printer automatically, nor could it detect it when I went through manual steps for a network printer.

I suspect it may have something to do with IPv6 - when I use the global module from the command line, I get `ipp-printer listening on: http://[2001:0:9d38:6abd:34f7:1a09:3f57:ff3b]:3000`. I tried using that as an IP for Windows to detect - still no printer found.

Am I missing something? How can I use this module in Windows?

**Comment by watson** [comment]
@TravelingTechGuy Yeah, Windows will most likely not be able to detect it automatically unless there is some way to add Bonjour/Zeroconf to Windows that I don't know about. So you need to add it as a network printer manually as you also tried.

I'm not entirely sure why you still couldn't get it to work, but I haven't tested IPv6 support that thoroughly yet, so it might be related to that. I have tested it using IPv4 on Windows 10 and that worked. I used this guide:
http://www.zedt.eu/tech/windows/installing-an-ipp-printer-in-windows-10/

Can you tell me if you did the same thing or if you did something different?

**Comment by watson** [comment]
@TravelingTechGuy I didn't take any screenshots when I did it on Win10, but you can check [my steps on XP here](https://github.com/watson/ipp-printer/issues/1#issuecomment-160475297)

**Comment by TravelingTechGuy** [comment]
@watson tried following the Windows 10 instructions to the letter. 

- I ran the global module in the folder `C:\Users\myuser\Code\printer\`.
- I picked a random printer name for the driver. 
- I'm getting an error when trying to print the test page
```
$ ipp-printer
ipp-printer listening on: http://[2001:0:5ef5:79fd:20a1:1fa3:bc6b:c2d7]:3000
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\myuser\Code\printer\ipp-printer_2015-12-28T23:32:52.202Z.ps'
    at Error (native)
```

**Comment by watson** [comment]
@TravelingTechGuy Seems like it doesn't have permissions to create files in the current directory. Can it be a permission issue?

It's trying to create a file on this line:
https://github.com/watson/ipp-printer/blob/a85dd138dc2edfe256d6d07d9805d6a599b6cb79/bin.js#L18

**Comment by TravelingTechGuy** [comment]
Hmm, I wonder why. My user is the admin. And the folder is under my user's profile anyway.
Perhaps it's printing under a different user (like a print spooler). At any rate, I'd like to use the non-global version. I hope that won't happen under that condition.

**Comment by watson** [comment]
@TravelingTechGuy Turned out to be the colons in the filename that Windows didn't like. I've updated the CLI to add the epoch to the filename instead of the ISO timestamp. It's released in v0.10.7 on npm.

Thanks for reporting this :smiley:

**Comment by TravelingTechGuy** [comment]
@watson great! Glad it was a real issue eventually :)

Thanks for the hard work!

**Comment by matthiasg** [comment]
it did work here too on windows 10. but windows prompted me to specify a driver first ? is this expected ? which driver should i select ? i selected the microsoft print to pdf but still i would like not to have to choose this.

**Comment by matthiasg** [comment]
installing the [Apple Bonjour Print Services for Windows](https://support.apple.com/kb/dl999?locale=en_US) did the same, it detected the printer but asks for a printer driver then.

**Comment by watson** [comment]
@matthiasg yeah, unfortunately windows doesn't have a default IPP driver (as far as I know). So you need to chose a dummy printer driver manually. I usually just chose `HP Color LaserJet 2500 PS Class Driver`

There might be a way to tell windows witch driver to use by modifying the TXT record when advertising or modifying some of the IPP responses. I'll have to look into that.

**Comment by otaroo** [comment]
@watson  Have no **HP Color LaserJet 2500 PS Class Driver** in Windows 7 x64
What should i do?

**Comment by Vlad-Polupan** [comment]
@otaroo Try to use **Microsoft PS Class Driver**
